[profile.default]
solc_version = "0.8.18"
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/confracts=lib/openzeppelin-contract/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
